// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/MuxiKeStack/bff/ioc"
	"github.com/MuxiKeStack/bff/pkg/ginx"
	"github.com/MuxiKeStack/bff/web"
)

// Injectors from wire.go:

func InitWebServer() *ginx.Server {
	logger := ioc.InitLogger()
	cmdable := ioc.InitRedis()
	handler := ioc.InitJwtHandler(cmdable)
	client := ioc.InitEtcdClient()
	userServiceClient := ioc.InitUserClient(client)
	ccnuServiceClient := ioc.InitCCNUClient(client)
	userHandler := web.NewUserHandler(handler, userServiceClient, ccnuServiceClient)
	courseServiceClient := ioc.InitCourseClient(client)
	evaluationServiceClient := ioc.InitEvaluationClient(client)
	courseHandler := web.NewCourseHandler(handler, courseServiceClient, evaluationServiceClient, userServiceClient, logger)
	questionServiceClient := ioc.InitQuestionClient(client)
	questionHandler := web.NewQuestionHandler(questionServiceClient, userServiceClient, logger)
	server := ioc.InitGinServer(logger, handler, userHandler, courseHandler, questionHandler)
	return server
}
