http:
  addr: ":8088"

redis:
  addr: "localhost:6379"

etcd:
  endpoints:
    - "localhost:12379"

grpc:
  client:
    ccnu:
      endpoint: "discovery:///ccnu"
      retryCnt: 3    # 具备重试装饰时的重试次数
    user:
      endpoint: "discovery:///user"
    course:
      endpoint: "discovery:///course"
    evaluation:
      endpoint: "discovery:///evaluation"
    question:
      endpoint: "discovery:///question"


jwt:
  jwtKey: "mc8QAegcrdOmGwQthrx3cgd2hd8CVfaH"
  refreshKey: "Hx9g8TinCH30NqckgKfFO2KkbaeCUMmj"