definitions:
  ginx.Result:
    properties:
      code:
        description: 错误码，非 0 表示失败
        type: integer
      data: {}
      msg:
        description: 错误或成功 描述
        type: string
    type: object
  web.GradeVo:
    properties:
      final:
        type: number
      regular:
        type: number
      term:
        type: string
      total:
        type: number
      year:
        type: string
    type: object
  web.LoginByCCNUReq:
    properties:
      password:
        description: 密码
        type: string
      student_id:
        description: 学号
        type: string
    type: object
  web.ProfileCourseVo:
    properties:
      evaluated:
        type: boolean
      id:
        type: integer
      name:
        type: string
      teacher:
        type: string
      term:
        description: 学年，1/2/3
        type: string
      year:
        description: 学期，2018
        type: string
    type: object
  web.PublicCourseVo:
    properties:
      credit:
        type: number
      id:
        type: integer
      name:
        type: string
      school:
        type: string
      teacher:
        type: string
      type:
        type: string
    type: object
  web.UserEditReq:
    properties:
      avatar:
        type: string
      nickname:
        type: string
    type: object
  web.UserProfileVo:
    properties:
      avatar:
        type: string
      ctime:
        type: integer
      id:
        type: integer
      new:
        description: 是否为新用户，新用户尚未编辑过个人信息
        type: boolean
      nickname:
        type: string
      studentId:
        type: string
      utime:
        type: integer
    type: object
  web.UserPublicProfileVo:
    properties:
      avatar:
        type: string
      id:
        type: integer
      nickname:
        type: string
    type: object
info:
  contact: {}
paths:
  /courses/{courseId}/detail:
    get:
      consumes:
      - application/json
      description: 根据课程ID获取课程详情信息
      parameters:
      - description: 课程ID
        in: path
        name: courseId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Result'
            - properties:
                data:
                  $ref: '#/definitions/web.PublicCourseVo'
              type: object
      summary: 获取课程详情
      tags:
      - 课程
  /courses/{courseId}/grades:
    get:
      consumes:
      - application/json
      description: 根据课程ID获取课程的成绩信息
      parameters:
      - description: 课程ID
        in: path
        name: courseId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Result'
            - properties:
                data:
                  $ref: '#/definitions/web.GradeVo'
              type: object
      summary: 获取课程成绩
      tags:
      - 课程
  /courses/list:
    get:
      consumes:
      - application/json
      description: 获取用户的课程列表
      parameters:
      - description: 年份，格式为YYYY
        in: query
        name: year
        type: string
      - description: 学期，如1、2、3
        in: query
        name: term
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Result'
            - properties:
                data:
                  $ref: '#/definitions/web.ProfileCourseVo'
              type: object
      summary: 我的课程列表
      tags:
      - 课程
  /users/:userId/profile:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Result'
            - properties:
                data:
                  $ref: '#/definitions/web.UserPublicProfileVo'
              type: object
      summary: 获取用户信息[公开]
      tags:
      - 用户
  /users/edit:
    post:
      consumes:
      - application/json
      parameters:
      - description: 编辑用户信息请求体
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/web.UserEditReq'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/ginx.Result'
      summary: 编辑个人信息
      tags:
      - 用户
  /users/login_ccnu:
    post:
      consumes:
      - application/json
      description: 通过学号和密码进行登录认证
      parameters:
      - description: 登录请求体
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/web.LoginByCCNUReq'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/ginx.Result'
      summary: ccnu登录
      tags:
      - 用户
  /users/logout:
    post:
      consumes:
      - application/json
      description: 通过短token登出
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/ginx.Result'
      summary: 登出(销毁token)
      tags:
      - 用户
  /users/profile:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/ginx.Result'
            - properties:
                data:
                  $ref: '#/definitions/web.UserProfileVo'
              type: object
      summary: 获取用户信息[自己]
      tags:
      - 用户
  /users/refresh_token:
    get:
      consumes:
      - application/json
      description: 通过长token刷新短token
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/ginx.Result'
      summary: 刷新短token
      tags:
      - 用户
swagger: "2.0"
