definitions:
  ginx.Result:
    properties:
      code:
        description: 错误码，非 0 表示失败
        type: integer
      data: {}
      msg:
        description: 错误或成功 描述
        type: string
    type: object
  web.LoginByCCNUReq:
    properties:
      password:
        description: 密码
        type: string
      student_id:
        description: 学号
        type: string
    type: object
info:
  contact: {}
paths:
  /users/login_ccnu:
    post:
      consumes:
      - application/json
      description: 通过学号和密码进行登录认证
      parameters:
      - description: 登录请求体
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/web.LoginByCCNUReq'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            $ref: '#/definitions/ginx.Result'
      summary: ccnu登录
      tags:
      - 用户
swagger: "2.0"
